package de.yochyo.pixiv_api.types

enum class Mode {
    DAY, WEEK, MONTH, DAY_MALE, DAY_FEMALE, WEEK_ORIGINAL, WEEK_ROOKIE, DAY_R18, DAY_MALE_R18, DAY_FEMALE_R18,
    WEEK_R18, WEEK_R18G, DAY_MANGA, WEEK_MANGA, MONTH_MANGA, WEEK_ROOKIE_MANGA,
    DAY_R18_MANGA, WEEK_R18_MANGA, WEEK_R18G_MANGA;
}
